const path = require('node:path');
const { spawn } = require('node:child_process');
process.env.electron_config_cache = path.join(__dirname, '..', '.electron-cache');
process.env.ELECTRON_CACHE = process.env.electron_config_cache;
const electron = require('electron');
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
const child = spawn(electron, [path.join(__dirname, '..'), ...process.argv.slice(2)], { stdio: 'inherit', windowsHide: true, env });
child.on('error', e => { console.error(e.message); process.exitCode = 1; });
child.on('exit', code => { process.exitCode = code ?? 1; });
process.on('SIGINT', () => child.kill());
