const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { Store } = require('../src/core.cjs');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
async function until(fn, message) { const deadline = Date.now() + 15000; while (Date.now() < deadline) { if (await fn()) return; await delay(100); } throw new Error(message); }
module.exports = async ({ app, panel, getPetWindow, store, tick, root, dataDir }) => {
  const artifacts = path.join(root, 'artifacts'); fs.mkdirSync(artifacts, { recursive: true });
  const errors = [];
  for (const w of [panel, getPetWindow()]) w.webContents.on('console-message', (_e, details) => { if (details.level === 'error') errors.push(details.message); });
  try {
    await until(async () => await panel.webContents.executeJavaScript('window.__ready === true') && await getPetWindow().webContents.executeJavaScript('window.__ready === true'), '窗口没有成功加载');
    assert.equal(getPetWindow().isAlwaysOnTop(), true); assert.equal(getPetWindow().isFocusable(), false);
    assert.equal(await panel.webContents.executeJavaScript('typeof require'), 'undefined');
    const alpha = await getPetWindow().webContents.executeJavaScript(`Array.from(document.querySelector('#pet').getContext('2d').getImageData(0,0,192,208).data).filter((v,i)=>i%4===3&&v>0).length`);
    assert.ok(alpha > 1000, '宠物应正确解码并显示');
    fs.writeFileSync(path.join(artifacts, 'home.png'), (await panel.webContents.capturePage()).toPNG());
    await panel.webContents.executeJavaScript(`document.querySelector('[data-tab="reminders"]').click(); document.getElementById('quick-reminder').value='明天 09:30 项目讨论 · 开发验证'; document.getElementById('parse-reminder').click(); document.getElementById('meeting-lead').value='0'; document.getElementById('meeting-lead').dispatchEvent(new Event('input')); document.getElementById('reminder-form').requestSubmit();`);
    await until(() => store.state.reminders.length === 1, '会议表单未保存');
    assert.equal(store.state.reminders[0].title, '项目讨论 · 开发验证');
    assert.equal(new Date(store.state.reminders[0].meetingAt).getHours(), 9);
    assert.equal(new Date(store.state.reminders[0].meetingAt).getMinutes(), 30);
    await panel.webContents.executeJavaScript(`document.querySelector('[data-tab="settings"]').click(); document.getElementById('setting-quiet').click();`);
    await until(() => store.state.settings.quiet, '免打扰未保存');
    const timed = await panel.webContents.executeJavaScript(`window.petdesk.addReminder({title:'会议要开始啦 · 提醒验证',meetingAt:new Date(Date.now()+1200).toISOString(),leadMinutes:0})`);
    await until(() => store.state.reminders.find(r => r.id === timed.id)?.status === 'active', '到期提醒没有触发');
    assert.equal(await getPetWindow().webContents.executeJavaScript(`document.getElementById('bubble').hidden`), true);
    assert.equal(new Store(dataDir).state.reminders.find(r => r.id === timed.id).status, 'active');
    await panel.webContents.executeJavaScript(`document.getElementById('setting-quiet').click();`);
    await until(async () => !(await getPetWindow().webContents.executeJavaScript(`document.getElementById('bubble').hidden`)), '关闭免打扰后提醒没有出现');
    await panel.webContents.executeJavaScript(`document.querySelector('[data-tab="reminders"]').click()`);
    await delay(250);
    fs.writeFileSync(path.join(artifacts, 'reminders.png'), (await panel.webContents.capturePage()).toPNG());
    fs.writeFileSync(path.join(artifacts, 'pet-reminder.png'), (await getPetWindow().webContents.capturePage()).toPNG());
    await getPetWindow().webContents.executeJavaScript(`document.getElementById('snooze').click()`);
    await until(() => store.state.reminders.find(r => r.id === timed.id)?.status === 'pending', '稍后提醒没有保存');
    assert.ok(Date.parse(store.state.reminders.find(r => r.id === timed.id).dueAt) > Date.now() + 290000);
    store.update(s => { s.reminders.find(r => r.id === timed.id).dueAt = new Date(Date.now() - 1000).toISOString(); }); tick();
    await until(async () => !(await getPetWindow().webContents.executeJavaScript(`document.getElementById('bubble').hidden`)), '重新到期没有显示');
    await getPetWindow().webContents.executeJavaScript(`document.getElementById('ack').click()`);
    await until(() => store.state.reminders.find(r => r.id === timed.id)?.status === 'done', '确认提醒没有保存');
    assert.equal(new Store(dataDir).state.reminders.find(r => r.id === timed.id).status, 'done');
    assert.equal(getPetWindow().getBounds().width, 320, '默认窗口应缩小到 60%');
    fs.writeFileSync(path.join(artifacts, 'pet-compact.png'), (await getPetWindow().webContents.capturePage()).toPNG());
    await getPetWindow().webContents.executeJavaScript(`window.petdesk.dockPet()`);
    await until(() => !!store.state.dock && getPetWindow().getBounds().width <= 64, '侧边收起未生效');
    const dockedWidth = getPetWindow().getBounds().width;
    const { screen } = require('electron');
    const dockedBounds = getPetWindow().getBounds();
    const dockedArea = screen.getDisplayMatching(dockedBounds).workArea;
    assert.ok(dockedBounds.x >= dockedArea.x && dockedBounds.x + dockedBounds.width <= dockedArea.x + dockedArea.width, '侧边入口必须完整位于屏幕内');
    assert.deepEqual(new Store(dataDir).state.dock, store.state.dock);
    await new Promise(resolve => { getPetWindow().webContents.once('did-finish-load', resolve); getPetWindow().reload(); });
    await until(() => getPetWindow().webContents.executeJavaScript('window.__ready === true && !document.getElementById("edge-tab").hidden'), '重新加载后收起状态丢失');
    const dockedReminder = await panel.webContents.executeJavaScript(`window.petdesk.addReminder({title:'收起时的提醒',meetingAt:new Date(Date.now()+1000).toISOString(),leadMinutes:0})`);
    await until(() => store.state.reminders.find(r => r.id === dockedReminder.id)?.status === 'active', '收起时提醒未触发');
    assert.equal(getPetWindow().getBounds().width, dockedWidth, '到期提醒不应强制展开');
    await until(() => getPetWindow().webContents.executeJavaScript('!document.getElementById("edge-count").hidden'), '侧边未显示提醒数量');
    fs.writeFileSync(path.join(artifacts, 'pet-docked.png'), (await getPetWindow().webContents.capturePage()).toPNG());
    await getPetWindow().webContents.executeJavaScript(`document.getElementById('edge-tab').click()`);
    await until(() => !store.state.dock && getPetWindow().getBounds().width === 320, '点击侧边未展开');
    assert.equal(await getPetWindow().webContents.executeJavaScript('document.getElementById("bubble").hidden'), false);
    await panel.webContents.executeJavaScript(`window.petdesk.settings({scale:0.45})`);
    await until(() => getPetWindow().webContents.executeJavaScript('Math.abs(document.getElementById("pet").getBoundingClientRect().width - 64.8) < 1'), '迷你尺寸未生效');
    assert.equal(await getPetWindow().webContents.executeJavaScript('getComputedStyle(document.getElementById("bubble-title")).fontSize'), '17px');
    await getPetWindow().webContents.executeJavaScript(`document.getElementById('bubble-title').textContent = '这是一个比较长的会议标题，用来确认两行文字在迷你宠物上也可以完整地展示';`);
    assert.ok(await getPetWindow().webContents.executeJavaScript(`document.getElementById('bubble').getBoundingClientRect().top >= 0`), '两行标题气泡不应被裁切');
    fs.writeFileSync(path.join(artifacts, 'pet-readable-mini.png'), (await getPetWindow().webContents.capturePage()).toPNG());
    await panel.webContents.executeJavaScript(`document.getElementById('import-pet').click()`);
    await delay(250);
    assert.equal(await panel.webContents.executeJavaScript(`document.getElementById('import-dialog').open`), true);
    assert.ok(await panel.webContents.executeJavaScript(`document.querySelector('.import-guide').textContent.includes('codex-pets.net')`));
    fs.writeFileSync(path.join(artifacts, 'import-guide.png'), (await panel.webContents.capturePage()).toPNG());
    await panel.webContents.executeJavaScript(`document.getElementById('import-close').click()`);
    if (process.env.PETDESK_TEST_ZIP) await require('./smoke-import.cjs')({ panel, getPetWindow, store, root, dataDir });
    await require('./smoke-edge.cjs')({ panel, getPetWindow, root });
    await require('./smoke-eye.cjs')({ panel, getPetWindow, store, root, dataDir });
    assert.deepEqual(errors, [], '界面控制台应无错误');
    fs.writeFileSync(path.join(artifacts, 'smoke-result.json'), JSON.stringify({ passed: true, checks: ['windows-ready', 'sandboxed-renderer', 'sprite-decoded', 'form-save', 'real-timer', 'quiet-mode', 'persistence', 'snooze', 'acknowledge', 'compact-size', 'dock-persist-reload', 'docked-reminder-badge', 'expand', 'mini-size'], at: new Date().toISOString() }, null, 2));
    console.log('Electron smoke: PASS (14 checks). Screenshots: artifacts/'); app.quit();
  } catch (e) { fs.writeFileSync(path.join(artifacts, 'smoke-error.txt'), `${e.stack}\n${JSON.stringify({ bounds: getPetWindow()?.getBounds(), state: store.snapshot() }, null, 2)}`); console.error(e); app.exit(1); }
};
