const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { Store } = require('../src/core.cjs');
const { powerMonitor } = require('electron');
const delay = ms => new Promise(resolve => setTimeout(resolve,ms));
module.exports = async ({panel, getPetWindow, store, root, dataDir}) => {
  const idle = powerMonitor.getSystemIdleTime;
  powerMonitor.getSystemIdleTime = () => 0;
  const run = code => panel.webContents.executeJavaScript(code);
  const pet = code => getPetWindow().webContents.executeJavaScript(code);
  try {
    await run(`window.petdesk.settings({eyeBreak:true,eyeMinutes:45,quiet:false})`);
    assert.equal(new Store(dataDir).state.settings.eyeMinutes,45);
    await run(`window.petdesk.previewEyeBreak()`); await delay(100);
    const active = store.state.reminders.filter(r=>r.status==='active');
    if (active.length) assert.equal(await pet(`document.getElementById('ack').textContent`),'知道啦','会议优先');
    for(const r of active) await run(`window.petdesk.reminderAction(${JSON.stringify({id:r.id,action:'done'})})`);
    await delay(100);
    assert.equal(await pet(`document.getElementById('ack').textContent`),'去歇会儿');
    const first = await pet(`document.getElementById('bubble-title').textContent`);
    assert.ok(await pet(`document.getElementById('bubble').getBoundingClientRect().top >= 0`));
    fs.writeFileSync(path.join(root,'artifacts','eye-break.png'),(await getPetWindow().webContents.capturePage()).toPNG());
    await pet(`document.getElementById('snooze').click()`); await delay(100);
    assert.equal((await run('window.petdesk.init()')).eyeReminder,null);
    await run(`window.petdesk.previewEyeBreak()`); await delay(100);
    assert.notEqual(await pet(`document.getElementById('bubble-title').textContent`),first);
    await run(`window.petdesk.settings({quiet:true})`); await delay(100);
    assert.equal(await pet(`document.getElementById('bubble').hidden`),true);
    await run(`window.petdesk.settings({quiet:false}); document.querySelector('[data-tab="settings"]').click(); window.scrollTo(0,0)`); await delay(200);
    fs.writeFileSync(path.join(root,'artifacts','eye-settings.png'),(await panel.webContents.capturePage()).toPNG());
    await pet(`document.getElementById('ack').click()`); await delay(100);
    assert.equal((await run('window.petdesk.init()')).eyeReminder,null);
    await run(`window.petdesk.previewEyeBreak();`);
    await run(`window.petdesk.settings({eyeBreak:false})`); await delay(100);
    assert.equal((await run('window.petdesk.init()')).eyeReminder,null);
    assert.equal(new Store(dataDir).state.settings.eyeBreak,false);
    console.log('Eye break smoke: PASS (settings, meeting priority, readable bubble, snooze, rotation, quiet, acknowledge, disable).');
  } finally { powerMonitor.getSystemIdleTime = idle; }
};
